#ifndef __NAME_STATIC_H__
#define __NAME_STATIC_H__

#ifndef __NAME_DEFINE__
#include "name.h"

#define DECLARE_NAME(name)	extern Name g_n##name;
#define NAME(name) g_n##name
void NAME_RemoveAll();
#endif

DECLARE_NAME(NO_NAME)

DECLARE_NAME(ON_PRESS)
DECLARE_NAME(ON_RELEASE)
DECLARE_NAME(ON_HOVER)
DECLARE_NAME(ON_END_HOVER)
DECLARE_NAME(ON_VALIDATE)
DECLARE_NAME(ON_PAUSE)
DECLARE_NAME(ON_RESUME)
DECLARE_NAME(ON_DRAG)
DECLARE_NAME(ON_DROP)

DECLARE_NAME(CAMERA)

// DAE
DECLARE_NAME(COLLADA)
DECLARE_NAME(asset)
DECLARE_NAME(library_animations)
DECLARE_NAME(library_animation_clips)
DECLARE_NAME(library_cameras)
DECLARE_NAME(library_controllers)
DECLARE_NAME(library_effects)
DECLARE_NAME(library_force_fields)
DECLARE_NAME(library_geometries)
DECLARE_NAME(library_images)
DECLARE_NAME(library_lights)
DECLARE_NAME(library_materials)
DECLARE_NAME(library_nodes)
DECLARE_NAME(library_physics_materials)
DECLARE_NAME(library_physics_models)
DECLARE_NAME(library_physics_scenes)
DECLARE_NAME(library_visual_scenes)
DECLARE_NAME(scene)
DECLARE_NAME(instance_physics_scene)
DECLARE_NAME(instance_visual_scene)
DECLARE_NAME(extra)
DECLARE_NAME(image)
DECLARE_NAME(data)
DECLARE_NAME(init_from)
DECLARE_NAME(material)
DECLARE_NAME(instance_effect)
DECLARE_NAME(effect)
DECLARE_NAME(annotate)
DECLARE_NAME(newparam)
DECLARE_NAME(fx_profile_abstract)
DECLARE_NAME(profile_COMMON)
DECLARE_NAME(geometry)
DECLARE_NAME(convex_mesh)
DECLARE_NAME(mesh)
DECLARE_NAME(spline)
DECLARE_NAME(source)
DECLARE_NAME(vertices)
DECLARE_NAME(input)
DECLARE_NAME(lines)
DECLARE_NAME(linestrips)
DECLARE_NAME(polygons)
DECLARE_NAME(polylist)
DECLARE_NAME(triangles)
DECLARE_NAME(p)
DECLARE_NAME(trifans)
DECLARE_NAME(tristrips)
DECLARE_NAME(controller)
DECLARE_NAME(skin)
DECLARE_NAME(morph)
DECLARE_NAME(bind_shape_matrix)
DECLARE_NAME(joints)
DECLARE_NAME(vertex_weights)
DECLARE_NAME(vcount)
DECLARE_NAME(v)
DECLARE_NAME(animation)
DECLARE_NAME(sampler)
DECLARE_NAME(OUTPUT)
DECLARE_NAME(INTERPOLATION)
DECLARE_NAME(channel)
DECLARE_NAME(node)
DECLARE_NAME(JOINT)
DECLARE_NAME(lookat)
DECLARE_NAME(matrix)
DECLARE_NAME(rotate)
DECLARE_NAME(scale)
DECLARE_NAME(skew)
DECLARE_NAME(translate)
DECLARE_NAME(instance_camera)
DECLARE_NAME(instance_controller)
DECLARE_NAME(instance_geometry)
DECLARE_NAME(instance_light)
DECLARE_NAME(instance_node)
DECLARE_NAME(visual_scene)
DECLARE_NAME(IDREF_array)
DECLARE_NAME(Name_array)
DECLARE_NAME(bool_array)
DECLARE_NAME(float_array)
DECLARE_NAME(int_array)
DECLARE_NAME(technique_common)
DECLARE_NAME(technique)
DECLARE_NAME(NORMAL)
DECLARE_NAME(POSITION)
DECLARE_NAME(TEXCOORD)
DECLARE_NAME(VERTEX)

DECLARE_NAME(BMP)
DECLARE_NAME(PNG)
DECLARE_NAME(TIF)

DECLARE_NAME(World)
DECLARE_NAME(Entity)
DECLARE_NAME(Component)
DECLARE_NAME(Param)
DECLARE_NAME(Name)
DECLARE_NAME(Value)
DECLARE_NAME(Type)
DECLARE_NAME(Pos)
DECLARE_NAME(Rot)
DECLARE_NAME(Scale)
DECLARE_NAME(Hide)
DECLARE_NAME(Color)
#endif
