#pragma once
#ifndef __PROFILER_OPTICK_H__
#define __PROFILER_OPTICK_H__

#ifdef USE_OPTICK
#define OPTICK_ENABLE_GPU_VULKAN 0

#include INCLUDE_LIB(LIB_OPTICK, include/optick.h)
#pragma LINK_LIB(LIB_OPTICK,lib/x64/release/OptickCore.lib)
#define OPTICK_EXE "../src/lib/"STRINGIFY_MACRO(EXPAND(LIB_OPTICK))"/Optick.exe"

#define PROFILER_OPTICK_SCOPED(__NAME__)	OPTICK_EVENT(__NAME__)
#define PROFILER_OPTICK_START(__NAME__)		OPTICK_PUSH(__NAME__)
#define PROFILER_OPTICK_STOP()				OPTICK_POP()
#define PROFILER_OPTICK_FRAME(__NAME__)		OPTICK_FRAME(__NAME__)
#define PROFILER_OPTICK_SHUTDOWN()			OPTICK_SHUTDOWN()
#define PROFILER_OPTICK_THREAD(__NAME__)	OPTICK_THREAD(__NAME__)
#else
#define PROFILER_OPTICK_SCOPED(__NAME__)
#define PROFILER_OPTICK_START(__NAME__)		
#define PROFILER_OPTICK_STOP()		
#define PROFILER_OPTICK_FRAME(__NAME__)
#define PROFILER_OPTICK_SHUTDOWN()			
#define PROFILER_OPTICK_THREAD(__NAME__)	
#endif

#endif